name: Testing using Codebuild Runners

on:
  workflow_dispatch:

jobs:
  nest:
    name: Test
    environment: Development
    runs-on: codebuild-mkahnlein-testing-cb-project-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-small
    steps:
      - run: echo $db_user
      - run: echo $vpc_id

