name: Testing using Codebuild Runners

on:
  workflow_dispatch:

jobs:
  nest:
    name: Test
    runs-on: codebuild-testing-cb-project-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-small
    steps:
      - run: echo "Hello World!"
